"""
QMS document framework for SaMD (Class II/III, multi-market: NMPA / CE / FDA).
Organized into 4 implementation phases.
"""

MARKETS = ["NMPA", "CE", "FDA"]

QMS_PHASES = [
    {
        "id": "phase1",
        "name": "第一阶段：体系基础",
        "duration": "第 1-2 个月",
        "description": "建立质量管理体系的基本架构，明确职责权限，搭建文件和记录管理框架",
        "documents": [
            {
                "id": "QM-001",
                "name": "质量手册",
                "short": "质量手册",
                "type": "manual",
                "standards": ["ISO 13485 §4.2.2", "21 CFR Part 820", "EU MDR Annex IX"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "描述 QMS 范围、政策、过程及其相互关系，是体系的纲领性文件",
            },
            {
                "id": "SOP-001",
                "name": "文件控制程序",
                "short": "文件控制",
                "type": "procedure",
                "standards": ["ISO 13485 §4.2.4"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定文件的起草、评审、批准、发布、变更、作废和销毁流程",
            },
            {
                "id": "SOP-002",
                "name": "记录控制程序",
                "short": "记录控制",
                "type": "procedure",
                "standards": ["ISO 13485 §4.2.5"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定质量记录的标识、存储、检索、保护、保留期限和处置要求",
            },
            {
                "id": "SOP-003",
                "name": "管理评审程序",
                "short": "管理评审",
                "type": "procedure",
                "standards": ["ISO 13485 §5.6"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "规定管理评审的输入、输出、频率和记录要求",
            },
            {
                "id": "SOP-004",
                "name": "人员培训与能力管理程序",
                "short": "人员培训",
                "type": "procedure",
                "standards": ["ISO 13485 §6.2"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "规定岗位资质要求、培训计划制定、培训效果评估和记录管理",
            },
            {
                "id": "SOP-005",
                "name": "基础设施与工作环境管理程序",
                "short": "基础设施",
                "type": "procedure",
                "standards": ["ISO 13485 §6.3", "ISO 13485 §6.4"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "medium",
                "description": "规定软件开发环境、服务器、网络等基础设施的管理和维护要求",
            },
            {
                "id": "FORM-001",
                "name": "文件发布/变更申请表",
                "short": "文件变更申请",
                "type": "form",
                "standards": ["ISO 13485 §4.2.4"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "用于记录文件的发布和变更申请、评审批准过程",
            },
            {
                "id": "FORM-002",
                "name": "培训记录表",
                "short": "培训记录",
                "type": "form",
                "standards": ["ISO 13485 §6.2"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "记录员工培训内容、时间、讲师和效果评估结果",
            },
            {
                "id": "FORM-003",
                "name": "管理评审报告模板",
                "short": "管理评审报告",
                "type": "form",
                "standards": ["ISO 13485 §5.6"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "记录管理评审的输入数据、讨论内容和决策输出",
            },
        ],
    },
    {
        "id": "phase2",
        "name": "第二阶段：软件开发过程",
        "duration": "第 2-4 个月",
        "description": "建立符合 IEC 62304 的软件全生命周期管理过程，覆盖需求、设计、实现、测试、发布",
        "documents": [
            {
                "id": "SOP-010",
                "name": "软件开发生命周期程序",
                "short": "软件开发",
                "type": "procedure",
                "standards": ["IEC 62304 §5", "YY/T 0664", "21 CFR Part 820.30"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "定义软件开发全生命周期各阶段的活动、输入、输出和验收准则",
            },
            {
                "id": "SOP-011",
                "name": "软件需求管理程序",
                "short": "需求管理",
                "type": "procedure",
                "standards": ["IEC 62304 §5.2", "ISO 13485 §7.3.3"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定软件需求的获取、分析、文档化、评审、追踪和变更管理过程",
            },
            {
                "id": "SOP-012",
                "name": "软件配置管理与版本控制程序",
                "short": "配置管理",
                "type": "procedure",
                "standards": ["IEC 62304 §8"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定软件版本管理、变更控制、基线管理和配置审计要求",
            },
            {
                "id": "SOP-013",
                "name": "软件验证与确认程序",
                "short": "验证与确认",
                "type": "procedure",
                "standards": ["IEC 62304 §5.6", "ISO 13485 §7.3.7", "21 CFR Part 820.70(i)"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定软件单元测试、集成测试、系统测试和最终验证的方法和准则",
            },
            {
                "id": "SOP-014",
                "name": "软件缺陷与问题管理程序",
                "short": "缺陷管理",
                "type": "procedure",
                "standards": ["IEC 62304 §9"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "规定软件缺陷的发现、记录、分类、修复和关闭流程",
            },
            {
                "id": "SOP-015",
                "name": "软件发布与部署程序",
                "short": "发布管理",
                "type": "procedure",
                "standards": ["IEC 62304 §5.8", "ISO 13485 §7.5"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "规定软件版本发布的审批、打包、部署、验证和回滚流程",
            },
            {
                "id": "SOP-016",
                "name": "设计变更控制程序",
                "short": "设计变更",
                "type": "procedure",
                "standards": ["ISO 13485 §7.3.9", "21 CFR Part 820.30(i)"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定设计变更的申请、影响评估、审批、实施和验证流程",
            },
            {
                "id": "FORM-010",
                "name": "软件需求规格说明（SRS）模板",
                "short": "需求规格说明",
                "type": "form",
                "standards": ["IEC 62304 §5.2.2"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "记录软件功能需求、性能需求、安全需求和接口需求",
            },
            {
                "id": "FORM-011",
                "name": "软件架构设计文档模板",
                "short": "架构设计文档",
                "type": "form",
                "standards": ["IEC 62304 §5.3"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "描述软件整体架构、模块划分、接口设计和技术选型",
            },
            {
                "id": "FORM-012",
                "name": "测试计划与测试报告模板",
                "short": "测试计划/报告",
                "type": "form",
                "standards": ["IEC 62304 §5.6.1"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "定义测试范围、测试策略、测试用例设计方法和通过准则",
            },
            {
                "id": "FORM-013",
                "name": "软件发布清单",
                "short": "发布清单",
                "type": "form",
                "standards": ["IEC 62304 §5.8"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "发布前的检查清单，确认所有必要活动已完成",
            },
        ],
    },
    {
        "id": "phase3",
        "name": "第三阶段：风险与质量控制",
        "duration": "第 3-5 个月",
        "description": "建立风险管理、可用性工程、网络安全、CAPA、内审等质量控制过程",
        "documents": [
            {
                "id": "SOP-020",
                "name": "风险管理程序",
                "short": "风险管理",
                "type": "procedure",
                "standards": ["ISO 14971:2019", "IEC 62304 §7", "YY/T 0316"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定风险分析、风险评价、风险控制、剩余风险评价和风险管理报告的全流程",
            },
            {
                "id": "SOP-021",
                "name": "可用性工程程序",
                "short": "可用性工程",
                "type": "procedure",
                "standards": ["IEC 62366-1:2015", "FDA HFE Guidance"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "规定用户研究、使用规范、用户界面设计、形成性评价和总结性评价的流程",
            },
            {
                "id": "SOP-022",
                "name": "网络安全管理程序",
                "short": "网络安全",
                "type": "procedure",
                "standards": ["YY/T 1833.1", "FDA Cybersecurity Guidance", "IMDRF Cybersecurity"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定软件全生命周期网络安全活动，包括威胁建模、安全测试和漏洞管理",
            },
            {
                "id": "SOP-023",
                "name": "纠正和预防措施（CAPA）程序",
                "short": "CAPA",
                "type": "procedure",
                "standards": ["ISO 13485 §8.5.2", "ISO 13485 §8.5.3", "21 CFR Part 820.100"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定不合格、投诉、审核发现的根因分析、纠正措施制定、实施和有效性验证",
            },
            {
                "id": "SOP-024",
                "name": "内部审核程序",
                "short": "内部审核",
                "type": "procedure",
                "standards": ["ISO 13485 §8.2.2", "21 CFR Part 820.22"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定内审计划制定、审核员资质、审核执行、发现记录和跟踪关闭流程",
            },
            {
                "id": "SOP-025",
                "name": "不合格品控制程序",
                "short": "不合格品控制",
                "type": "procedure",
                "standards": ["ISO 13485 §8.3", "21 CFR Part 820.90"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "规定不合格软件/服务的识别、隔离、评审处置和记录要求",
            },
            {
                "id": "SOP-026",
                "name": "顾客投诉处理程序",
                "short": "投诉处理",
                "type": "procedure",
                "standards": ["ISO 13485 §8.2.2", "21 CFR Part 820.198"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "规定投诉受理、分类、调查、处理、回复和记录全流程",
            },
            {
                "id": "SOP-027",
                "name": "数据保护与隐私管理程序",
                "short": "数据保护",
                "type": "procedure",
                "standards": ["GDPR", "个人信息保护法", "数据安全法"],
                "markets": ["NMPA", "CE"],
                "priority": "high",
                "description": "规定个人健康数据的收集、存储、使用、传输、删除和泄露响应流程",
            },
            {
                "id": "FORM-020",
                "name": "风险管理档案（RMF）模板",
                "short": "风险管理档案",
                "type": "form",
                "standards": ["ISO 14971:2019 §3.5"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "包含危害识别、风险分析、风险控制措施和剩余风险评价的完整档案",
            },
            {
                "id": "FORM-021",
                "name": "CAPA 表单",
                "short": "CAPA 表单",
                "type": "form",
                "standards": ["ISO 13485 §8.5.2"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "记录问题描述、根因分析、纠正措施、责任人和有效性验证",
            },
            {
                "id": "FORM-022",
                "name": "内审计划与报告模板",
                "short": "内审计划/报告",
                "type": "form",
                "standards": ["ISO 13485 §8.2.2"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "内审前计划和审核后发现汇总报告",
            },
            {
                "id": "FORM-023",
                "name": "软件安全分类报告模板",
                "short": "安全分类报告",
                "type": "form",
                "standards": ["IEC 62304 §4.3", "YY/T 0664"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "按照 IEC 62304 确定软件及各模块的安全分类（A/B/C）",
            },
        ],
    },
    {
        "id": "phase4",
        "name": "第四阶段：注册与上市后管理",
        "duration": "第 4-6 个月",
        "description": "建立注册申报、临床评价、上市后监督、警戒系统等注册合规过程",
        "documents": [
            {
                "id": "SOP-030",
                "name": "注册申报管理程序",
                "short": "注册申报",
                "type": "procedure",
                "standards": ["医疗器械注册与备案管理办法", "EU MDR Article 10", "21 CFR Part 807"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定产品注册/备案的准备、提交、沟通、维护和变更申报流程",
            },
            {
                "id": "SOP-031",
                "name": "临床评价程序",
                "short": "临床评价",
                "type": "procedure",
                "standards": ["医疗器械临床评价技术指导原则", "EU MDR Annex XIV", "21 CFR Part 860"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定临床数据收集、文献评价、等同性论证和临床评价报告编写流程",
            },
            {
                "id": "SOP-032",
                "name": "上市后监督（PMS）程序",
                "short": "上市后监督",
                "type": "procedure",
                "standards": ["ISO 13485 §8.2.1", "EU MDR Article 83", "21 CFR Part 820.198"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定上市后数据收集、趋势分析、定期安全更新报告（PSUR/PMCF）流程",
            },
            {
                "id": "SOP-033",
                "name": "医疗器械警戒与不良事件报告程序",
                "short": "警戒系统",
                "type": "procedure",
                "standards": ["医疗器械不良事件监测和再评价管理办法", "EU MDR Article 87", "21 CFR Part 803"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "critical",
                "description": "规定不良事件的识别、评估、上报时限、调查和预防措施制定",
            },
            {
                "id": "SOP-034",
                "name": "召回与现场纠正措施程序",
                "short": "召回管理",
                "type": "procedure",
                "standards": ["医疗器械召回管理办法", "EU MDR Article 89", "21 CFR Part 806"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "规定主动召回和强制召回的决策、执行、通报和效果评估流程",
            },
            {
                "id": "SOP-035",
                "name": "采购与供应商管理程序",
                "short": "供应商管理",
                "type": "procedure",
                "standards": ["ISO 13485 §7.4"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "规定外包开发商、云服务商、组件供应商的资质评估、合同管理和绩效监控",
            },
            {
                "id": "SOP-036",
                "name": "标识与可追溯性程序",
                "short": "标识追溯",
                "type": "procedure",
                "standards": ["ISO 13485 §7.5.3", "UDI 法规"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "规定软件版本标识、UDI 分配和全生命周期可追溯性要求",
            },
            {
                "id": "FORM-030",
                "name": "临床评价报告模板",
                "short": "临床评价报告",
                "type": "form",
                "standards": ["医疗器械临床评价技术指导原则", "MEDDEV 2.7/1"],
                "markets": ["NMPA", "CE"],
                "priority": "critical",
                "description": "包含评价计划、文献搜索策略、数据分析和结论的完整临床评价文档",
            },
            {
                "id": "FORM-031",
                "name": "上市后监督计划（PMSP）模板",
                "short": "上市后监督计划",
                "type": "form",
                "standards": ["EU MDR Article 84"],
                "markets": ["CE"],
                "priority": "high",
                "description": "定义上市后数据收集方法、评估频率和报告计划",
            },
            {
                "id": "FORM-032",
                "name": "不良事件报告表",
                "short": "不良事件报告",
                "type": "form",
                "standards": ["医疗器械不良事件监测和再评价管理办法"],
                "markets": ["NMPA"],
                "priority": "critical",
                "description": "向 NMPA 上报不良事件的标准表格和填写指南",
            },
            {
                "id": "FORM-033",
                "name": "供应商评估表",
                "short": "供应商评估",
                "type": "form",
                "standards": ["ISO 13485 §7.4.1"],
                "markets": ["NMPA", "CE", "FDA"],
                "priority": "high",
                "description": "对供应商进行初始评估和年度复评的标准表单",
            },
        ],
    },
]

DOC_TYPE_LABELS = {
    "manual": "质量手册",
    "procedure": "程序文件",
    "form": "记录表单",
    "plan": "计划",
    "report": "报告",
}

PRIORITY_LABELS = {
    "critical": "必需",
    "high": "重要",
    "medium": "建议",
}

def get_all_documents() -> list[dict]:
    docs = []
    for phase in QMS_PHASES:
        for doc in phase["documents"]:
            docs.append({**doc, "phase_id": phase["id"], "phase_name": phase["name"]})
    return docs

def get_document_by_id(doc_id: str) -> dict | None:
    for doc in get_all_documents():
        if doc["id"] == doc_id:
            return doc
    return None

def get_stats() -> dict:
    all_docs = get_all_documents()
    return {
        "total": len(all_docs),
        "by_type": {t: sum(1 for d in all_docs if d["type"] == t) for t in ["manual", "procedure", "form"]},
        "by_priority": {p: sum(1 for d in all_docs if d["priority"] == p) for p in ["critical", "high", "medium"]},
        "phases": len(QMS_PHASES),
    }
